name: Build

on: [push, pull_request, workflow_dispatch] 

jobs:
  build:
    name: Build for CSS on Ubuntu
    runs-on: ubuntu-20.04

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout AMBuild
        uses: actions/checkout@v4
        with:
          repository: alliedmodders/ambuild
          path: ambuild

      - name: Install AMBuild
        uses: BSFishy/pip-action@v1
        with:
          packages: ./ambuild

      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y gcc-multilib g++-multilib

      - name: Checkout MetaMod
        uses: actions/checkout@v4
        with:
            repository: alliedmodders/metamod-source
            path: metamod-source
            submodules: recursive

      - name: Checkout SourceMod
        uses: actions/checkout@v4
        with:
          repository: alliedmodders/sourcemod
          ref: 1.12-dev
          path: sourcemod
          submodules: recursive

      - name: Checkout hl2sdk-css
        uses: actions/checkout@v4
        with:
          repository: alliedmodders/hl2sdk
          ref: css
          path: hl2sdk-css

      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          fetch-depth: 99999
          path: extension

      - name: Build
        working-directory: extension
        shell: bash
        run: |
          mkdir build && cd build
          python ../configure.py --enable-optimize --sdks=css
          ambuild

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TransmitManager-CSS-Linux
          path: extension/build/package